# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('winston_api', '0002_event_speak'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='source',
            field=models.CharField(max_length=50),
        ),
        migrations.DeleteModel(
            name='Source',
        ),
    ]
