# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('winston_api', '0003_auto_20170311_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='source',
        ),
    ]
