# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-11 21:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('message_id', models.CharField(max_length=25, primary_key=True, serialize=False)),
                ('thread_id', models.CharField(max_length=25)),
                ('arrive_datetime', models.DateTimeField(auto_now_add=True)),
                ('picked_up', models.BooleanField(default=False)),
            ],
        ),
    ]
